routes/admin.php
<?php

Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'as'         => 'admin.',
    'middleware' => [
        'auth',
        'role:admin',
    ],
], function () {
    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('rooms', 'RoomsController@index')->name('rooms.index');
    Route::get('bookings', 'BookingsController@index')->name('bookings.index');
    Route::post('booking-available','BookingsController@available')->name('bookings.available');
    Route::post('booking-confirm','BookingsController@confirmBooking')->name('bookings.confirm-booking');
    Route::get('promotions', 'PromotionsController@index')->name('promotions.index');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::get('prices', 'PricesController@index')->name('prices.index');

    Route::group([
        'prefix'    => 'api',
        'namespace' => 'Api',
        'as'        => 'api.',
    ], function () {
        Route::resource('rooms', 'RoomsController');
        Route::resource('bookings', 'BookingsController');
        Route::resource('promotions', 'PromotionsController');
        Route::put('bookings/{booking}/approve', 'BookingsController@approve')->name('bookings.approve');
        Route::put('bookings/{booking}/disapprove', 'BookingsController@disapprove')->name('bookings.disapprove');
        Route::resource('users', 'UsersController');
        Route::get('prices', 'RoomsController@getPrices')->name('prices.get');
        Route::put('prices', 'RoomsController@updatePrices')->name('prices.update');
    });
});

routes/web.php
<?php


Route::group([
    'as' => 'web.',
    'namespace' => 'Web',
], function () {
    Route::view('/', 'app.web.index')->name('index');
    //Route::view('account-edit', 'app.web.account-edit')->name('account-edit');
    Route::get('historial', 'BookingsController@history')->name('history');
    Route::view('reservas', 'app.web.reservations')->name('reservations');
    Route::get('reserva-promocion/{promotion}', 'PromotionsController@bookingPromotion')->name('reservations.promotions');
    Route::post('comprobar-reserva', 'BookingsController@checkAvailability')->name('reservation-check');
    Route::view('reserva-realizada', 'app.web.reservation-success')->name('reservation-success');
    Route::view('editar-reserva', 'app.web.reservation-edit')->name('reservation-edit');
    Route::view('habitaciones', 'app.web.rooms')->name('rooms');
    Route::view('servicios', 'app.web.services')->name('services');
    Route::view('aparts', 'app.web.aparts')->name('aparts');
    Route::view('contacto', 'app.web.contacts')->name('contacts');
    Route::post('contacto', 'ContactsController@send')->name('contacts');
    Route::get('paquetes', 'PromotionsController@getPromotions')->name('packages');

    Route::post('confirm-booking', 'BookingsController@confirmBooking')->name('confirm-booking');
    Route::post('payment-ipn', 'PaymentsController@paymentReceived')->name('payment-received');
    Route::get('payment-success', 'PaymentsController@paymentSuccess')->name('payment-success');
    Route::get('payment-pending', 'PaymentsController@paymentPending')->name('payment-pending');
    Route::get('payment-failure', 'PaymentsController@paymentFailure')->name('payment-failure');


    Route::group([
        'middleware' => 'auth'
    ], function () {
        Route::get('pay-promotion/{promotion}', 'PaymentsController@payPromotion')->name('pay-promotion');
    });
});

Route::get('/inicio', 'HomeController@index')->name('home');
Route::get('mi-perfil', 'UsersController@profile')->name('profile');
Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Http/Controllers/Admin/Api/BookingsController.php
<?php

namespace App\Http\Controllers\Admin\Api;

use App\Booking;
use App\Definitions\BookingDefinition;
use App\Http\Controllers\Controller;
use App\Http\Requests\BookingStoreRequest;
use App\Http\Requests\BookingUpdateRequest;
use App\Transformers\BookingTransformer;
use Illuminate\Http\Request;

class BookingsController extends Controller
{
    public function index(Request $request)
    {
        $bookings = Booking::query();

        if ($search = $request->input('search'))
            $bookings->where('number', 'like', '%' . $search . '%');

        if ($orderName = $request->input('order_name'))
            $bookings->orderBy($orderName, $request->input('order_type'));
        else
            $bookings->orderBy('id','desc');
        $bookings = $bookings->paginate(5);

        return BookingTransformer::prepare($bookings);
    }

    public function store(BookingStoreRequest $request)
    {
        $booking = new Booking();
        $this->fill($request, $booking);
        $booking->save();

        return $booking;
    }

    public function update(BookingUpdateRequest $request, Booking $booking)
    {
        $this->fill($request, $booking);
        $booking->save();

        return $booking;
    }

    public function destroy(Booking $booking)
    {
        $booking->delete();

        return ['ok'];
    }

    public function fill(Request $request, Booking $booking)
    {
        $booking->number = $request->input('number');
        $booking->places = $request->input('places');
        $booking->double = $request->input('double');
        $booking->type = $request->input('type');
    }

    public function approve(Booking $booking)
    {
        $booking->status = BookingDefinition::APPROVED_STATUS;
        $booking->save();
    }

    public function disapprove(Booking $booking)
    {
        $booking->status = BookingDefinition::REJECTED_STATUS;
        $booking->save();
    }
}

app/Http/Controllers/Admin/BookingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Booking;
use App\Definitions\BookingDefinition;
use App\Price;
use App\Services\BookingService;
use Carbon\Carbon;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BookingsController extends Controller
{
    public function index()
    {
        return view('app.admin.bookings.index');
    }

    public function available(Request $request)
    {

        $this->validate(request(), [
            'guests_number'=>'required|numeric|min:1',
            'start_at' => 'required|date_format:d/m/Y',
            'finish_at' => 'required|date_format:d/m/Y',
        ]);

        /** @var BookingService $bookingService */
        $bookingService = app(BookingService::class);

        /** @var Carbon $carbon */
        $carbon = app(Carbon::class);
        $startAt = $carbon->createFromFormat('d/m/Y', $request->input('start_at'));
        $finishAt = $carbon->createFromFormat('d/m/Y', $request->input('finish_at'));

        $days = $startAt->diffInDays($finishAt);

        $rooms = $bookingService->getAvailableOptions();

        $spa = $request->input('spa') ? $request->input('spa') : 0;
        $kids = $request->input('kids') ? $request->input('kids') : 0;
        $massages = $request->input('massages') ? $request->input('massages') : 0;

        $prices = Price::first();

        $additionalLabel = '';
        $additionalDetail = [];
        if ($spa > 0) {
            $additionalLabel .= '<p>- SPA & RELAX '.$spa.' días </p>';
            $additionalDetail['spa'] = [
                'days' => $spa,
                'total' => $spa * $prices->spa
            ];
        }

        if ($kids > 0) {
            $additionalLabel .= '<p>- Kid\'s TIME '.$kids.' días </p>';
            $additionalDetail['kids'] = [
                'days' => $kids,
                'total' => $kids * $prices->kids
            ];
        }

        if ($massages > 0) {
            $additionalLabel .= '<p>- MASAJES '.$massages.' días</p>';
            $additionalDetail['massages'] = [
                'days' => $massages,
                'total' => $massages * $prices->massages
            ];
        }

        $additionalTotal = $spa * $prices->spa * $days + $kids * $prices->kids * $days + $massages * $prices->massages * $days;

        $options = [];

        $suggested = [];
        foreach ($rooms['preferred'] as $room) {
            $options[] = [
                'rooms' => $room['rooms'],
                'rooms_price' => $room['price'],
                'total' => $room['price'] + $additionalTotal,
                'type' => $room['rooms'][0]->type,
                'additional' => [
                    'detail' => $additionalDetail,
                    'label' => $additionalLabel,
                    'total' => $additionalTotal,
                ],
                'data' => $request->all(),
            ];
        }


        foreach ($rooms['suggested'] as $room) {
            $suggested[] = [
                'rooms' => $room['rooms'],
                'rooms_price' => $room['price'],
                'total' => $room['price'] + $additionalTotal,
                'type' => $room['rooms'][0]->type,
                'additional' => [
                    'label' => $additionalLabel,
                    'total' => $additionalTotal,
                ],
                'data' => $request->all(),
            ];
        }

        $users = User::all();

        return view('app.admin.bookings.available')->withOptions($options)->withSuggested($suggested)->withUsers($users);
    }

    public function confirmBooking(Request $request)
    {
        // Creo registro de reserva
        // redirecciono hacia el pago

        $data = json_decode($request->input('data'));

//        dd($data);

        $booking = new Booking;

        $booking->user_id = $request->input('user_id');
        $booking->start_at = Carbon::createFromFormat('d/m/Y', $data->data->start_at);
        $booking->finish_at = Carbon::createFromFormat('d/m/Y', $data->data->finish_at);
        $booking->children = 0;
        $booking->minors = 0;
        $booking->cradle = 0;
        $booking->observation = '';
        $booking->price = $data->total;
        $booking->type = $data->type;
        $booking->guests = $data->data->guests_number;
        $booking->additional = json_encode($data->additional);
        $booking->status = BookingDefinition::APPROVED_STATUS;
        $booking->save();

        foreach ($data->rooms as $room) {
            $booking->rooms()->attach($room->id);
        }



        return redirect()->route('admin.bookings.index');
    }
}

app/Http/Controllers/Admin/Datatable/BookingTable.php
<?php

namespace App\Http\Controllers\Admin\Datatable;

class BookingTable extends BaseTable
{
    protected $columns = [
        [
            'title' => 'Creado',
            'name' => 'created_at',
        ],
        [
            'title' => 'Usuario',
            'name' => 'user',
            'type'=>'slot'
        ],
        [
            'title' => 'Desde',
            'name' => 'start_at',
            'type' => 'date',
        ],
        [
            'title' => 'Hasta',
            'name' => 'finish_at',
            'type' => 'date',
        ],
        [
            'title' => 'Invitados',
            'name' => 'guests',
            'type' => 'integer',
        ],

        [
            'title' => 'Estado',
            'name' => 'status',
        ],

    ];
}

app/Http/Controllers/Web/BookingsController.php
<?php

namespace App\Http\Controllers\Web;

use App\Booking;
use App\Definitions\BookingDefinition;
use App\Http\Controllers\Controller;
use App\Mail\SendBooking;
use App\Price;
use App\Services\BookingService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;


class BookingsController extends Controller
{
    public function checkAvailability(Request $request)
    {
        $this->validate(request(), [
            'start_at' => 'required|date_format:d/m/Y',
            'finish_at' => 'required|date_format:d/m/Y',
        ]);

        /** @var BookingService $bookingService */
        $bookingService = app(BookingService::class);

        /** @var Carbon $carbon */
        $carbon = app(Carbon::class);
        $startAt = $carbon->createFromFormat('d/m/Y', $request->input('start_at'));
        $finishAt = $carbon->createFromFormat('d/m/Y', $request->input('finish_at'));

        $days = $startAt->diffInDays($finishAt);

        $rooms = $bookingService->getAvailableOptions();

        $spa = $request->input('spa') ? $request->input('spa') : 0;
        $kids = $request->input('kids') ? $request->input('kids') : 0;
        $massages = $request->input('massages') ? $request->input('massages') : 0;

        $prices = Price::first();

        $additionalLabel = '';
        $additionalDetail = [];
        if ($spa > 0) {
            $additionalLabel .= '<p>- SPA & RELAX '.$spa.' días </p>';
            $additionalDetail['spa'] = [
                'days' => $spa,
                'total' => $spa * $prices->spa
            ];
        }

        if ($kids > 0) {
            $additionalLabel .= '<p>- Kid\'s TIME '.$kids.' días </p>';
            $additionalDetail['kids'] = [
                'days' => $kids,
                'total' => $kids * $prices->kids
            ];
        }

        if ($massages > 0) {
            $additionalLabel .= '<p>- MASAJES '.$massages.' días</p>';
            $additionalDetail['massages'] = [
                'days' => $massages,
                'total' => $massages * $prices->massages
            ];
        }

        $additionalTotal = $spa * $prices->spa * $days + $kids * $prices->kids * $days + $massages * $prices->massages * $days;

        $options = [];

        $suggested = [];
        foreach ($rooms['preferred'] as $room) {
            $options[] = [
                'rooms' => $room['rooms'],
                'rooms_price' => $room['price'],
                'total' => $room['price'] + $additionalTotal,
                'type' => $room['rooms'][0]->type,
                'additional' => [
                    'detail' => $additionalDetail,
                    'label' => $additionalLabel,
                    'total' => $additionalTotal,
                ],
                'data' => $request->all(),
            ];
        }



        foreach ($rooms['suggested'] as $room) {
            $suggested[] = [
                'rooms' => $room['rooms'],
                'rooms_price' => $room['price'],
                'total' => $room['price'] + $additionalTotal,
                'type' => $room['rooms'][0]->type,
                'additional' => [
                    'label' => $additionalLabel,
                    'total' => $additionalTotal,
                ],
                'data' => $request->all(),
            ];
        }
        return view('app.web.reservations-options')->withOptions($options)->withSuggested($suggested);
    }

    public function history()
    {
        $bookings = auth()->user()->bookings;

//        foreach ($bookings as $booking) {
//            $additional = $booking->additionalData['label'];
////            dd($additional);
//        }


        return view('app.web.history')->withBookings($bookings);
    }

    public function confirmBooking(Request $request)
    {
        // Creo registro de reserva
        // redirecciono hacia el pago

        $data = json_decode($request->input('data'));

//        dd($data);

        $booking = new Booking;

        $booking->user_id = auth()->user()->id;
        $booking->start_at = Carbon::createFromFormat('d/m/Y',$data->data->start_at);
        $booking->finish_at = Carbon::createFromFormat('d/m/Y',$data->data->finish_at);
        $booking->children = 0;
        $booking->minors = 0;
        $booking->cradle = 0;
        $booking->observation = '';
        $booking->price=$data->total;
        $booking->type=$data->type;
        $booking->guests=$data->data->guests_number;
        $booking->additional=json_encode($data->additional);
        $booking->status=BookingDefinition::PENDING_STATUS;
        $booking->save();

        foreach($data->rooms as $room){
            $booking->rooms()->attach($room->id);
        }

        //enviar mail para notificar

        Mail::to(config('mail.contact'))->send(new SendBooking($booking));

        return redirect()->route('web.reservation-success');
    }


}

resources/views/app/admin/bookings/available.blade.php
@extends('layouts.admin')
@section('content-header')
    <section class="content-header">
        <h1>
            Reservas
        </h1>
    </section>
@endsection
@section('content')

    <div class="box box-solid">
        <div class="box-body">
            <article class="top_content">
                <div>
                    <div class="mensajes_post_form" id="post_check" style="display:block;">
                        @if(count($options)>0)
                            <table class="table">
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col">HUÉSP.</th>
                                    <th scope="col">HABIT.</th>
                                    <th scope="col">CHECK-IN</th>
                                    <th scope="col">CHECK-OUT</th>
                                    <th scope="col">OPCIONALES</th>
                                    <th scope="col">PRECIO TOTAL</th>
                                    <th scope="col"></th>
                                </tr>
                                @foreach($options as $option)
                                    <tr>
                                        <td>{{ $option['type']=='normal'?'Hotel':'Apart' }}</td>
                                        <td>{{ $option['data']['guests_number'] }}</td>
                                        <td>
                                            @foreach($option['rooms'] as $room)
                                                <span>1 hab. p/{{ $room->places }} personas </span>
                                        @endforeach
                                        <td>{{ $option['data']['start_at'] }}</td>
                                        <td>{{ $option['data']['finish_at'] }}</td>
                                        <td>
                                            {!! empty($option['additional']['label'])?'-': $option['additional']['label'] !!}
                                        </td>
                                        <td>${{ $option['total'] }}</td>
                                        <td>
                                            <form action="{{ route('admin.bookings.confirm-booking') }}" method="post">
                                                {{ csrf_field() }}
                                                Usuario:
                                                <select name="user_id" class="select2">
                                                    @foreach($users as $user)
                                                        <option value="{{ $user->id }}">{{ $user->email }}</option>
                                                    @endforeach
                                                </select>
                                                <input type="hidden" name="data" value="{{ json_encode($option) }}">
                                                <button class="btn btn-primary">RESERVAR</button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach
                            </table>

                        @else
                            <h1>no hay disponibilidad para tu selección...</h1>
                        @endif

                        @if(count($suggested)>0)

                            <p><b>TAMBIÉN PODÉS TOMAR EN CUENTA ESTAS OPCIONES!</b></p>
                            <table class="table">
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col">HUÉSP.</th>
                                    <th scope="col">HABIT.</th>
                                    <th scope="col">CHECK-IN</th>
                                    <th scope="col">CHECK-OUT</th>
                                    <th scope="col">OPCIONALES</th>
                                    <th scope="col">PRECIO TOTAL</th>
                                    <th scope="col"></th>
                                </tr>
                                @foreach($suggested as $option)
                                    <tr>
                                        <td>{{ $option['type']=='normal'?'Hotel':'Apart' }}</td>
                                        <td>{{ $option['data']['guests_number'] }}</td>
                                        <td>
                                            @foreach($option['rooms'] as $room)
                                                <div>1 hab. p/{{ $room->places }} personas</div>
                                            @endforeach
                                        </td>
                                        <td>{{ $option['data']['start_at'] }}</td>
                                        <td>{{ $option['data']['finish_at'] }}</td>
                                        <td>
                                            {!! empty($option['additional']['label'])?'-': $option['additional']['label'] !!}
                                        </td>
                                        <td>${{ $option['total'] }}</td>
                                        <td>
                                            <form action="{{ route('admin.bookings.confirm-booking') }}" method="post">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="data" value="{{ json_encode($option) }}">
                                                Usuario:
                                                <select name="user_id" class="select2">
                                                    @foreach($users as $user)
                                                        <option>{{ $user->email }}</option>
                                                    @endforeach
                                                </select>
                                                <button class="btn btn-primary">RESERVAR</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>

                        @endif

                    </div>
                </div>
            </article>
        </div>
        <!-- /.box-body -->
    </div>
@endsection

@section('scripts')
    @parent
    <script src="{{ asset('public/vendors/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    <script>
        $('.select2').select2();
    </script>
@endsection

resources/views/app/admin/bookings/index.blade.php
@extends('layouts.admin')
@section('content-header')
    <section class="content-header">
        <h1>
            Reservas
        </h1>
    </section>
@endsection
@section('content')
    <div class="box box-solid">
        <div class="box-body">
            <booking-management
                    base-route="{{ route('admin.bookings.index') }}"
                    api-route="{{ route('admin.api.bookings.index') }}"
                    :datatable-config="{{ \App\Http\Controllers\Admin\Datatable\BookingTable::getColumns() }}">
            </booking-management>
        </div>
    </div>

    <div class="box box-solid">
        <div class="box-header">
            <h2>Revisar disponibilidad de reserva</h2>
        </div>
        <form role="form" method="post" action="{{ route('admin.bookings.available') }}">
            {{ csrf_field() }}
            <div class="box-body">
                @include('includes.messages')
                <div class="col-md-6">
                    <div class="form-group">
                        <label>
                            <input checked name="room_type" value="normal" type="radio"> HOTEL
                        </label>
                        <label>
                            <input name="room_type" value="apart" type="radio"> APART
                        </label>
                    </div>
                    <div class="form-group">
                        <label>CANT. HUÉSPEDES</label>
                        <input name="guests_number" type="number" value="1" class="form-control" id="exampleInputEmail1"
                               placeholder="">
                    </div>
                    <div class="form-group">
                        <label>Desde:</label>

                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input value="{{ old('start_at') }}" name="start_at" type="text"
                                   class="form-control pull-right datepicker">
                        </div>
                        <!-- /.input group -->
                    </div>

                    <div class="form-group">
                        <label>Hasta:</label>

                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input value="{{ old('finish_at') }}" name="finish_at" type="text"
                                   class="form-control pull-right datepicker">
                        </div>
                        <!-- /.input group -->
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label>
                            <input checked name="tipo_cama" value="double" type="radio"> CAMA MATRIMONIAL
                        </label>
                        <label>
                            <input name="tipo_cama" value="single" type="radio"> INDIVIDUALES
                        </label>
                    </div>

                    <div class="form-group">
                        <label>MASAJES (días)</label>
                        <input name="massages" type="number" class="form-control" id="exampleInputEmail1"
                               placeholder="">
                    </div>
                    <div class="form-group">
                        <label>SPA & RELAX (días)</label>
                        <input name="spa" type="number" class="form-control" id="exampleInputEmail1" placeholder="">
                    </div>
                    <div class="form-group">
                        <label>KID'S TIME (días)</label>
                        <input name="kids" type="number" class="form-control" id="exampleInputEmail1" placeholder="">
                    </div>
                    <div class="checkbox">
                        <label>
                            <input name="cama_extra" value="extra" type="checkbox"> CAMA EXTRA
                        </label>
                    </div>
                </div>


            </div>

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Chequear</button>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
    @parent
    <script>
        //Date picker
        $('.datepicker').datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy'
        })

    </script>

@endsection