routes/admin.php
<?php

Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'as'         => 'admin.',
    'middleware' => [
        'auth',
        'role:admin',
    ],
], function () {
    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('rooms', 'RoomsController@index')->name('rooms.index');
    Route::get('bookings', 'BookingsController@index')->name('bookings.index');
    Route::post('booking-available','BookingsController@available')->name('bookings.available');
    Route::post('booking-confirm','BookingsController@confirmBooking')->name('bookings.confirm-booking');
    Route::get('promotions', 'PromotionsController@index')->name('promotions.index');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::get('prices', 'PricesController@index')->name('prices.index');

    Route::group([
        'prefix'    => 'api',
        'namespace' => 'Api',
        'as'        => 'api.',
    ], function () {
        Route::resource('rooms', 'RoomsController');
        Route::resource('bookings', 'BookingsController');
        Route::resource('promotions', 'PromotionsController');
        Route::put('bookings/{booking}/approve', 'BookingsController@approve')->name('bookings.approve');
        Route::put('bookings/{booking}/disapprove', 'BookingsController@disapprove')->name('bookings.disapprove');
        Route::resource('users', 'UsersController');
        Route::get('prices', 'RoomsController@getPrices')->name('prices.get');
        Route::put('prices', 'RoomsController@updatePrices')->name('prices.update');
    });
});

routes/web.php
<?php


Route::group([
    'as' => 'web.',
    'namespace' => 'Web',
], function () {
    Route::view('/', 'app.web.index')->name('index');
    //Route::view('account-edit', 'app.web.account-edit')->name('account-edit');
    Route::get('historial', 'BookingsController@history')->name('history');
    Route::view('reservas', 'app.web.reservations')->name('reservations');
    Route::get('reserva-promocion/{promotion}', 'PromotionsController@bookingPromotion')->name('reservations.promotions');
    Route::post('comprobar-reserva', 'BookingsController@checkAvailability')->name('reservation-check');
    Route::view('reserva-realizada', 'app.web.reservation-success')->name('reservation-success');
    Route::view('editar-reserva', 'app.web.reservation-edit')->name('reservation-edit');
    Route::view('habitaciones', 'app.web.rooms')->name('rooms');
    Route::view('servicios', 'app.web.services')->name('services');
    Route::view('aparts', 'app.web.aparts')->name('aparts');
    Route::view('contacto', 'app.web.contacts')->name('contacts');
    Route::post('contacto', 'ContactsController@send')->name('contacts');
    Route::get('paquetes', 'PromotionsController@getPromotions')->name('packages');

    Route::post('confirm-booking', 'BookingsController@confirmBooking')->name('confirm-booking');
    Route::post('payment-ipn', 'PaymentsController@paymentReceived')->name('payment-received');
    Route::get('payment-success', 'PaymentsController@paymentSuccess')->name('payment-success');
    Route::get('payment-pending', 'PaymentsController@paymentPending')->name('payment-pending');
    Route::get('payment-failure', 'PaymentsController@paymentFailure')->name('payment-failure');


    Route::group([
        'middleware' => 'auth'
    ], function () {
        Route::get('pay-promotion/{promotion}', 'PaymentsController@payPromotion')->name('pay-promotion');
    });
});

Route::get('/inicio', 'HomeController@index')->name('home');
Route::get('mi-perfil', 'UsersController@profile')->name('profile');
Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/includes/admin/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">{{ config('app.name') }}</a>.</strong> Todos los derechos reservados.
</footer>

resources/views/includes/admin/header.blade.php
<header class="main-header">
    <a href="{{ url('/') }}" class="logo text-center" style="overflow: visible">
        <span class="logo-mini"><img style="max-height:50px; padding:9px" class="img-responsive" src="{{ asset('/assets/web/images/iso_hotel_sierra_de_los_padres.png') }}"></span>
        <span class="logo-lg">Sierra de los Padres</span>
    </a>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
               <li>
                    <a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/includes/admin/scripts.blade.php
<!-- REQUIRED JS SCRIPTS -->
<script src="{{ asset('js/laroute.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/moment-with-locales.js') }}"></script>

<!-- AdminLTE App -->
<script src="{{ asset('assets/admin/dist/js/app.min.js') }}"></script>

<!-- Custom Coffeedevs -->
<script src="{{ asset('assets/admin/custom/js/coffeedevs.js') }}"></script>

<!-- SweetAlert -->
<script src="{{ asset('vendors/bower_components/sweetalert/dist/sweetalert.min.js') }}"></script>

<!-- bootstrap datepicker -->
<script src="{{ asset('assets/admin/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<!-- bootstrap timepicker -->
<!-- bootstrap time picker -->
<script src="{{ asset('assets/admin/plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>
<!-- InputMask -->
<script src="{{ asset('assets/admin/plugins/input-mask/jquery.inputmask.js') }}"></script>
<script src="{{ asset('assets/admin/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('assets/admin/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>


{{--<!-- fullCalendar 2.2.5 -->--}}
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>--}}
{{--<script src="{{ asset('assets/admin/plugins/fullcalendar/fullcalendar.min.js') }}"></script>--}}


<!-- Fileinput-->
<script src="{{ asset('vendors/fileinput/fileinput.min.js') }}"></script>

<script src="{{ asset('vendors/select2/select2.full.min.js') }}"></script>

<!-- Slimscroll -->
<script src="{{ asset('assets/admin/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>

<!-- Include AlgoliaSearch JS Client and autocomplete.js library -->
<script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
<script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>
<!-- Morris Charts -->
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="{{ asset('assets/admin/plugins/morris/morris.min.js') }}"></script>
<script src="{{ asset('js/helpers.js') }}"></script>



<script>

    $(document).ready(function () {
        //Date picker
        $('.datepicker').datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy'
        });
        moment.locale('es');
    });

    jQuery(window).load(function() {
        jQuery("#loader").delay(500).fadeOut();
    })
</script>

resources/views/includes/admin/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu">
            <li class="header">OPCIONES</li>
            <li @if(Request::url() == route('admin.home')) class="active"@endif>
                <a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
            </li>
            <li @if(Request::url() == route('admin.rooms.index')) class="active"@endif>
                <a href="{{ route('admin.rooms.index') }}"><i class="fa fa-key"></i> <span>Habitaciones</span></a>
            </li>
            <li @if(Request::url() == route('admin.bookings.index')) class="active"@endif>
                <a href="{{ route('admin.bookings.index') }}"><i class="fa fa-credit-card"></i> <span>Reservas</span></a>
            </li>
            <li @if(Request::url() == route('admin.promotions.index')) class="active"@endif>
                <a href="{{ route('admin.promotions.index') }}"><i class="fa fa-bullhorn"></i> <span>Promociones</span></a>
            </li>
            <li @if(Request::url() == route('admin.users.index')) class="active"@endif>
                <a href="{{ route('admin.users.index') }}"><i class="fa fa-user"></i> <span>Usuarios</span></a>
            </li>
            {{--<li @if(Request::url() == route('admin.prices.index')) class="active"@endif>--}}
                {{--<a href="{{ route('admin.prices.index') }}"><i class="fa fa-user"></i> <span>Precios</span></a>--}}
            {{--</li>--}}
        </ul>
    </section>
</aside>

resources/views/includes/admin/styles.blade.php
<!-- Bootstrap 3.3.6 -->
<link rel="stylesheet" href="{{ asset('assets/admin/bootstrap/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('assets/admin/dist/css/AdminLTE.css') }}">
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect.
  -->
<link rel="stylesheet" href="{{ asset('assets/admin/dist/css/skins/skin-purple-light.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/dist/css/skins/skin-blue.css') }}">
<!-- daterange picker -->
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/daterangepicker/daterangepicker.css') }}">
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/datepicker/datepicker3.css') }}">
<!-- timepicker -->
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/timepicker/bootstrap-timepicker.min.css') }}">

<link rel="stylesheet" href="{{ asset('assets/admin/plugins/fullcalendar/fullcalendar.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/fullcalendar/fullcalendar.print.css') }}" media="print">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

<link rel="stylesheet" href="{{ asset('vendors/select2/select2.min.css') }}">

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Vendors -->
<link rel="stylesheet" href="{{ asset('vendors/bower_components/sweetalert/dist/sweetalert.css') }}">
<link rel="stylesheet" href="{{ asset('vendors/fileinput/fileinput.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/custom/css/main.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/custom/css/theme.css') }}">
<!-- Morris -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">




<style>
    [v-cloak] .v-cloak--block {
        display: block;
    }
    [v-cloak] .v-cloak--inline {
        display: inline;
    }
    [v-cloak] .v-cloak--inlineBlock {
        display: inline-block;
    }
    [v-cloak] .v-cloak--hidden {
        display: none;
    }
    [v-cloak] .v-cloak--invisible {
        visibility: hidden;
    }
    .v-cloak--block,
    .v-cloak--inline,
    .v-cloak--inlineBlock {
        display: none;
    }


    .av-siteloader-cell {
        display: table-cell;
        vertical-align: middle;
    }

    .av-siteloader-wrap {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        width: 100%;
        height: 100%;
        z-index: 1000000;
        background: #fff;
    }
    .av-siteloader-inner {
        position: relative;
        display: table;
        width: 100%;
        height: 100%;
        text-align: center;
    }
</style>