routes/admin.php
<?php

Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'as'         => 'admin.',
    'middleware' => [
        'auth',
        'role:admin',
    ],
], function () {
    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('rooms', 'RoomsController@index')->name('rooms.index');
    Route::get('bookings', 'BookingsController@index')->name('bookings.index');
    Route::post('booking-available','BookingsController@available')->name('bookings.available');
    Route::post('booking-confirm','BookingsController@confirmBooking')->name('bookings.confirm-booking');
    Route::get('promotions', 'PromotionsController@index')->name('promotions.index');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::get('prices', 'PricesController@index')->name('prices.index');

    Route::group([
        'prefix'    => 'api',
        'namespace' => 'Api',
        'as'        => 'api.',
    ], function () {
        Route::resource('rooms', 'RoomsController');
        Route::resource('bookings', 'BookingsController');
        Route::resource('promotions', 'PromotionsController');
        Route::put('bookings/{booking}/approve', 'BookingsController@approve')->name('bookings.approve');
        Route::put('bookings/{booking}/disapprove', 'BookingsController@disapprove')->name('bookings.disapprove');
        Route::resource('users', 'UsersController');
        Route::get('prices', 'RoomsController@getPrices')->name('prices.get');
        Route::put('prices', 'RoomsController@updatePrices')->name('prices.update');
    });
});

routes/web.php
<?php


Route::group([
    'as' => 'web.',
    'namespace' => 'Web',
], function () {
    Route::view('/', 'app.web.index')->name('index');
    //Route::view('account-edit', 'app.web.account-edit')->name('account-edit');
    Route::get('historial', 'BookingsController@history')->name('history');
    Route::view('reservas', 'app.web.reservations')->name('reservations');
    Route::get('reserva-promocion/{promotion}', 'PromotionsController@bookingPromotion')->name('reservations.promotions');
    Route::post('comprobar-reserva', 'BookingsController@checkAvailability')->name('reservation-check');
    Route::view('reserva-realizada', 'app.web.reservation-success')->name('reservation-success');
    Route::view('editar-reserva', 'app.web.reservation-edit')->name('reservation-edit');
    Route::view('habitaciones', 'app.web.rooms')->name('rooms');
    Route::view('servicios', 'app.web.services')->name('services');
    Route::view('aparts', 'app.web.aparts')->name('aparts');
    Route::view('contacto', 'app.web.contacts')->name('contacts');
    Route::post('contacto', 'ContactsController@send')->name('contacts');
    Route::get('paquetes', 'PromotionsController@getPromotions')->name('packages');

    Route::post('confirm-booking', 'BookingsController@confirmBooking')->name('confirm-booking');
    Route::post('payment-ipn', 'PaymentsController@paymentReceived')->name('payment-received');
    Route::get('payment-success', 'PaymentsController@paymentSuccess')->name('payment-success');
    Route::get('payment-pending', 'PaymentsController@paymentPending')->name('payment-pending');
    Route::get('payment-failure', 'PaymentsController@paymentFailure')->name('payment-failure');


    Route::group([
        'middleware' => 'auth'
    ], function () {
        Route::get('pay-promotion/{promotion}', 'PaymentsController@payPromotion')->name('pay-promotion');
    });
});

Route::get('/inicio', 'HomeController@index')->name('home');
Route::get('mi-perfil', 'UsersController@profile')->name('profile');
Route::resource('users', 'UsersController', ['only' => ['edit', 'update']]);

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Booking
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Room[] $rooms
 * @mixin \Eloquent
 * @property int $id
 * @property int $user_id
 * @property string $start_at
 * @property string $finish_at
 * @property int $children
 * @property int $minors
 * @property int $cradle
 * @property string $observation
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property-read \App\User $user
 * @property string additional
 * @property  guests
 * @property  type
 * @property  price
 * @property string status
 * @property mixed promotion_id
 * @property array|string guests
 * @property  type
 * @property array|string price
 * @property  guests
 * @property  type
 * @property  price
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereChildren($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereCradle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereFinishAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereMinors($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereObservation($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereStartAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Booking whereUserId($value)
 */
class Booking extends Model
{

    const STATUS_APPROVED = 'approved';
    const STATUS_REJECTED = 'rejected';

    public function rooms()
    {
        return $this->belongsToMany(Room::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getAdditionalDataAttribute()
    {
        return json_decode($this->attributes['additional'], true);
    }

    protected $dates = ['created_at', 'updated_at', 'start_at', 'finish_at'];

    public function getStatusTitleAttribute()
    {
        if ($this->status == self::STATUS_APPROVED) {
            return 'Aprobada';
        } elseif ($this->status == self::STATUS_REJECTED) {
            return 'Rechazada';
        } else return '';
    }
}

resources/views/app/web/account-edit.blade.php
@extends('layouts.web')

@section('content')
    <section>
        <article class="top_content">
            <div id="top_grande">
                <form class="form" method="POST" action="{{ route('users.update',Auth::id()) }}">
                    {{ csrf_field() }}
                    <h1>Editá tu cuenta</h1>
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <div>
                            <p>NOMBRE</p>
                            <input id="name" type="text" name="name" value="{{ $user->name }}" required autofocus>
                            @if ($errors->has('name'))
                                <div class="col-md-3 alert alert-success alert-dismissable fade in">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    {{ $errors->first('name') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <div>
                            <p>EMAIL</p>
                            <input id="email" type="email" name="email" value="{{ $user->email }}" required disabled>
                            @if ($errors->has('email'))
                                <div class="col-md-3 alert alert-success alert-dismissable fade in">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    {{ $errors->first('email') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div>
                        <p>TELEFONO</p>
                        <input type="tel" value="{{ $user->phone }}" name="phone" required>
                    </div>
                    <div>
                        <p>CIUDAD</p>
                        <input type="text" value="{{ $user->city }}" name="city" required>
                    </div>
                    <div>
                        <p>PROVINCIA</p>
                        <input type="text" value="{{ $user->state }}" name="state" required>
                    </div>
                    <div>
                        <p>PAÍS</p>
                        <input type="text" value="{{ $user->country }}" name="country" required>
                    </div>
                    {{ method_field('PUT') }}
                    <button name="edit_data" class="botones" type="submit" id="edit_data">GUARDAR DATOS</button>
                </form>
            </div>
        </article>
    </section>
@endsection

resources/views/app/web/contacts.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class="top_content">
            <div id="top_grande">

                <form class="form" method="post">
                    @include('includes.messages')
                    {{ csrf_field() }}
                    <h1>formulario de contacto</h1>
                    <div>
                        <input value="{{ old('name') }}" type="text" placeholder="Tu nombre y apellido" name="name">
                    </div>
                    <div>
                        <input value="{{ old('email') }}" type="email" placeholder="Tu e-mail" name="email">
                    </div>
                    <div>
                        <input value="{{ old('tel') }}" type="tel" placeholder="Un teléfono de contacto" name="tel">
                    </div>
                    <div>
                        <input value="{{ old('city') }}" type="text" placeholder="Ciudad" name="city">
                    </div>
                    <div>
                        <input value="{{ old('state') }}" type="text" placeholder="Provincia" name="state">
                    </div>
                    <div>
                        <input value="{{ old('country') }}" type="text" placeholder="País" name="country">
                    </div>
                    <div>
                        <textarea name="message" placeholder="Tu mensaje aquí...">{{ old('message') }}</textarea>
                    </div>
                    <button name="formulario_contacto" class="botones" type="submit" id="formulario_contacto">ENVIAR
                        CONSULTA
                    </button>
                </form>
                <div class="mensajes_post_form" style="display:none;">
                    <h1>no pudimos enviar tu consulta...</h1>
                    <p>Por favor, intentalo mas tarde. Si el problema persiste, comunicate con nosotros al 0223 463-0466
                        & 463-1624.</p>
                </div>
                <div class="mensajes_post_form" style="display:none;">
                    <h1>tu mensaje fue enviado con éxito!</h1>
                    <p>Te escribiremos o llamaremos por teléfono a la brevedad. Muchas gracias por tu contacto!</p>
                </div>
            </div>
        </article>
    </section>
    <iframe src="https://snazzymaps.com/embed/34823" style="border:none; width:100%;height:500px"></iframe>
   {{-- <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
    --}}{{--<div class="content_map">--}}{{--
        --}}{{--<div id='gmap_canvas'></div>--}}{{--
        --}}{{--<style>--}}{{--
            --}}{{--#gmap_canvas img {--}}{{--
                --}}{{--max-width: none !important;--}}{{--
                --}}{{--background: none !important--}}{{--
            --}}{{--}--}}{{--
        --}}{{--</style>--}}{{--
    --}}{{--</div>--}}{{--
    <script type='text/javascript'>function init_map() {
            var myOptions = {
                zoom: 14,
                center: new google.maps.LatLng(-37.9420857, -57.776034100000004),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);
            marker = new google.maps.Marker({
                map: map,
                position: new google.maps.LatLng(-37.9420857, -57.776034100000004)
            });
            infowindow = new google.maps.InfoWindow({content: '<strong>Sierra de los Padres natural hotel & aparts</strong><br>Av. Argentina y Arturo<br>'});
            google.maps.event.addListener(marker, 'click', function () {
                infowindow.open(map, marker);
            });
            infowindow.open(map, marker);
        }

        google.maps.event.addDomListener(window, 'load', init_map);
    </script>--}}

    @include('includes.web.promo-cuenta')
@endsection

resources/views/app/web/history.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class=" row top_content">
            <div>
                <div class="col-md-6 col-md-offset-3">
                    <h1>historial de reservas</h1>
                    <p><b>PARA OTRAS CONSULTAS ESCRIBINOS DESDE <a href="{{ route('web.contacts') }}"><< ACÁ >></a></b>
                    </p>
                    <table class="table_opciones">
                        <tbody>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">HUÉSP.</th>
                            <th scope="col">HABIT.</th>
                            <th scope="col">CHECK-IN</th>
                            <th scope="col">CHECK-OUT</th>
                            <th scope="col">OPCIONALES</th>
                            <th scope="col">ESTADO</th>
                            <th scope="col">PRECIO TOTAL</th>
                            {{--<th scope="col">ACCIONES</th>--}}
                        </tr>
                        @foreach($bookings as $booking)
                            <tr>
                                <td>{{ $booking->type=='apart'?'Apart':'Hotel' }}</td>
                                <td>{{ $booking->guests }}</td>
                                <td>
                                    @foreach($booking->rooms as $room)
                                        <span>1 hab. p/{{ $room->places }} personas </span>
                                    @endforeach
                                </td>
                                <td>{{ $booking->start_at->format('d/m/Y') }}</td>
                                <td>{{ $booking->finish_at->format('d/m/Y') }}</td>
                                <td>
                                    {!! empty($booking->additionalData['label'])?'-': $booking->additionalData['label'] !!}
                                </td>
                                <td title="{{ $booking->status_title }}">{!! $booking->status == App\Booking::STATUS_APPROVED
                                 ? '<i class="fa fa-check"></i>'
                                 : ($booking->status == App\Booking::STATUS_REJECTED ? '<i class="fa fa-cross"></i>' : '') !!} </td>
                                <td>${{ $booking->price }}</td>
                                {{--<td><a class="botones" href="{{ route('web.reservation-edit') }}">EDITAR</a><a--}}
                                {{--class="botones" id="boton_negro" href="#">CANCELAR</a></td>--}}
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
    </section>

    @include('includes.web.promo-cuenta')
@endsection

resources/views/app/web/index.blade.php
@extends('layouts.web')
@section('content')
    <section>
        @if(!empty(Session::get('edit')))
            <div class="col-md-3 alert alert-success alert-dismissable fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                El usuario fué creado con exito.
            </div>
        @endif
        <article class="top" id="top_index">
            <div>
                <div class="special">
                    <h1>SIERRA DE LOS PADRES</h1>
                    <p>natural hotel & aparts</p>
                </div>
            </div>
        </article>
    </section>

    <section>
        <article class="texto_institucional">
            <p><b>Es momento que vuelvas a tu esencia.</b><br>Que puedas volver a conectarte con vos mismo. Que vuelvas
                a
                respirar profundo... volver a tu tiempo.</p>
        </article>
    </section>

    <!--EL RESULTADO DEL SIGUIENTE FILTRADO ESTA EN resultado_filtrado_inicio.html -->

    <section>
        <article class="filtrado_rapido">
            <form method="post" action="{{ route('web.reservation-check') }}">
                {{ csrf_field() }}
                <div class="selects">
                    <div class="start_at">
                        <h2 class="destacado_gris">CHECK-IN</h2>
                        <p><span>&nbsp;</span></p><a class="select_date">▼</a>
                        <input type="hidden" name="start_at" id="start_at"
                               value="{{ Carbon\Carbon::today()->format('d/m/Y') }}">
                    </div>
                    <div id="vertical_linea"></div>
                    <div class="finish_at">
                        <h2 class="destacado_gris">CHECK-OUT</h2>
                        <p><span>&nbsp;</span></p><a class="select_date">▼</a>
                        <input type="hidden" name="finish_at" id="finish_at"
                               value="{{ Carbon\Carbon::today()->addWeek()->format('d/m/Y') }}">
                    </div>
                    <div id="vertical_linea"></div>
                    <div class="guests">
                        <h2 class="destacado_gris">HUÉSPEDES</h2>
                        <p><span>1</span></p><a class="toggle_guests">▼</a>
                        <input type="hidden" name="guests_number" value="1" id="guests_number">
                    </div>
                    <div style="padding:0;" id="div_boton_filtrado">
                        <button id="boton_salmon" class="check-reservation">CHEQUEAR</button>
                    </div>
                </div>
                <div class="select_huespedes" style="display:none;">
                    <a data-value="1">1</a>
                    <a data-value="2">2</a>
                    <a data-value="3">3</a>
                    <a data-value="4">4</a>
                    <a data-value="5">5</a>
                    <a data-value="6">6</a>
                    <a data-value="7">7</a>
                    <a data-value="8">8 o +</a>
                </div>
            </form>
        </article>
    </section>

    @if ($promotions->count() > 0)
        <section>
            <article class="paquetes">
                <div class="listados" id="bloque_previo">
                    <h1>Promociones & Paquetes <span>{{ ucfirst($current_month) }}</span></h1>
                    <p>OPORTUNIDADES ABIERTAS PARA TODOS LOS USUARIOS. <b>APLICABLES DURANTE EL MES
                            DE {{ strtoupper($current_month) }}.</b></p>
                    <p>Cada uno de nuestros paquetes y promociones buscan optimizar y maximizar la experiencia hotelera,
                        el
                        descanso y la libertad que significa ingresar en nuestro mundo. Además, sumamos los mejor
                        servicios
                        hoteleros, junto al profesionalismo y la cordialidad de cada uno de nosotros. Para que tu
                        estadía
                        sea
                        única. Y siempre quieras tener <b>tu tiempo</b>.</p>
                    <a href="{{ route('web.packages')  }}" target="_self" class="botones" id="boton_into_text">TODAS LAS
                        PROMOCIONES</a>
                </div>
                @foreach ($promotions as $promotion)
                    <div id="separador_table_cell"></div>
                    @include('includes.web.promotion', ['promotion' => $promotion])
                @endforeach
            </article>
        </section>
    @endif

    <section>
        <article class="content_promo_products" id="promo_cuenta">
            <div>
                <img src="{{ asset('assets/web/images/index/hotel.jpg') }}">
                <h2 class="destacado_gris">CON IDEAS FRESCAS</h2>
                <h1>Somos un hotel para tu tiempo.</h1>
                <p>Lo que nos hace diferentes no es sólo el entorno natural, que se destaca por las sierras y los prados
                    verdes. Tampoco sólo por nuestros SERVICIOS PREMIUM, entre los que se destacan nuestro SPA & RELAX y
                    piletas climatizadas. Lo que nos hace únicos es nuestra propia identidad. Nuestra forma de pensar y
                    crear. Porque sabemos que lo que necesitás para sentirte bien tenés que sentirlo naturalmente tuyo.
                    Porque sabemos que necesitas un respiro. TU TIEMPO.</p>
                <a href="{{ route('web.rooms') }}" target="_self" class="botones" id="boton_into_text">CONOCÉ NUESTRAS
                    HABITACIONES</a>
            </div>
            <div id="right">
                <img src="{{ asset('assets/web/images/index/aparts.jpg') }}">
                <h2 class="destacado_gris">LIBERTAD TOTAL</h2>
                <h1>Aparts con todos los servicios.</h1>
                <p>El desarrollo de este producto dentro del mismo predio nos ha permitido dar respuesta a las
                    necesidades
                    de muchos huéspedes que necesitan un espacio amplio y adecuado para la familia. Para un máximo de 6
                    personas, nuestros departamentos cuentan con todo lo que necesitás para tener junto a los tuyos de
                    una
                    estadía especial. Contarás además con todos los servicios dispuestos para el hotel, pudiendo elegir
                    libremente los adicionales de los que quieras disfrutar.</p>
                <a href="{{ route('web.aparts') }}" target="_self" class="botones" id="boton_into_text">MIRÁ NUESTROS
                    APARTS</a>
            </div>
        </article>
    </section>

    <section>
        <article class="paquetes" id="servicios">
            <div class="listados" id="bloque_previo">
                <h1>Nuestros Servicios Premium</h1>
                <p>Nuestra premisa es brindarte una estadía única, para que siempre encuentres en <b>SIERRA DE LOS
                        PADRES
                        natural hotel & aparts</b> un espacio donde volver a respirar, y tengas TU TIEMPO.</p>
                <p>Desayunos, estacionamiento exclusivo y protegido, wi-fi en cada espacio privado y de uso común del
                    hotel
                    y nuestros aparts, gimnasio completo, piscina descubierta, masajes, cancha de paddle, juegos de
                    mesa,
                    mesa de ping pong y metegol. Estos son algunos de nuestros servicios, que se suman a nuestro
                    reconocido
                    SPA & RELAX y KID'S TIME!</p>
                <a href="{{ route('web.reservations') }}" target="_self" class="botones" id="boton_into_text">HACÉ TU
                    RESERVA AHORA!</a>
            </div>
            <div id="separador_table_cell"></div>
            <div class="listados" id="paquete">
                <a href="{{ route('web.services') }}" target="_self"><img
                            src="{{ asset('assets/web/images/servicios/spa_&_relax_1.jpg') }}"></a>
                <div class="content_paquete">
                    <h2 class="destacado_gris">PARA CONECTARTE CON VOS MISMO</h2>
                    <h2>SPA & RELAX</h2>
                    <a href="{{ route('web.services') }}" target="_self">+ INFO</a>
                    <div class="precios">
                        <h2>DÍA DE SPA & RELAX >> $<span>600</span>.-</h2>
                    </div>
                    <h2 class="destacado_gris">SÓLO SE APLICA A ESTADÍAS. NO PUEDE SER ABORDADO DE MANERA INDEPENDIENTE
                        DE
                        ESTADÍAS EN HOTEL Y/O APARTS.</h2>
                    <a class="botones" href="{{ route('web.reservations') }}">DEFINIR FECHA >></a>
                </div>
            </div>
            <div id="separador_table_cell"></div>
            <div class="listados" id="paquete">
                <a href="{{ route('web.services') }}" target="_self"><img
                            src="{{ asset('assets/web/images/servicios/kids_time_1.jpg') }}"></a>
                <div class="content_paquete">
                    <h2 class="destacado_gris">HASTA LOS 12 AÑOS</h2>
                    <h2>KiD's TiMe!</h2>
                    <a href="{{ route('web.services') }}" target="_self">+ INFO</a>
                    <div class="precios">
                        <h2>Día completo >> $<span>300</span>.-</h2>
                    </div>
                    <h2 class="destacado_gris">SÓLO SE APLICA A ESTADÍAS. NO PUEDE SER ABORDADO DE MANERA INDEPENDIENTE
                        DE
                        ESTADÍAS EN HOTEL Y/O APARTS.</h2>
                    <a class="botones" href="{{ route('web.reservations') }}">DEFINIR FECHA >></a>
                </div>
            </div>
        </article>
    </section>

    @include('includes.web.promo-cuenta')
    @include('includes.web.testimoniales')
@endsection

@section('scripts')
    @include('includes.web.scripts.reservation')
@endsection

resources/views/app/web/packages.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class="top" id="header_paquetes">
            <div>
                <div id="content_title_page">
                    <h2 class="destacado_gris">DESCUENTOS || PROMOCIONES || PAQUETES</h2>
                    <h1>Promociones & Paquetes Octubre</h1>
                    <p><b>OPORTUNIDADES ÚNICAS CON DESCUENTOS IMPERDIBLES</b></p>
                </div>
            </div>
        </article>
    </section>

    <section>
        <article class="texto_institucional">
            <h2>¡NO LO DEJES PASAR!</h2>
            <p>PAGA ONLINE con MERCADOPAGO, en CUOTAS FIJAS con todas las tarjetas de todos los bancos!</p>
            <div id="tarjetas">
                <img src="{{ asset('assets/web/images/tarjetas/master.jpg') }}">
                <img src="{{ asset('assets/web/images/tarjetas/naranja.jpg') }}">
                <img src="{{ asset('assets/web/images/tarjetas/visa.jpg') }}">
                <img src="{{ asset('assets/web/images/tarjetas/pagofacil.jpg') }}">
                <img src="{{ asset('assets/web/images/tarjetas/provincia.jpg') }}">
                <img src="{{ asset('assets/web/images/tarjetas/rapipago.jpg') }}">
            </div>
        </article>
    </section>

    <section>
        <article class="row paquetes" id="servicios">
            @foreach ($promotions as $promotion)
                <div class="col-md-4">
                    @include('includes.web.promotion', ['promotion' => $promotion])
                </div>
            @endforeach
        </article>
    </section>

    @include('includes.web.promo-cuenta')
@endsection

resources/views/app/web/payment-result.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class=" row ">
            <div>
                @if($result=='success')
                    <div class="col-md-6 col-md-offset-3">
                        <div class="alert alert-success fade in alert-dismissable" style="width:50%;margin-top:18px;">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                            <strong>Proceso Exitoso!</strong> El hotel se comunicará con Ud. a la brevedad.
                        </div>
                    </div>
                @elseif($result=='pending')
                    <div class="col-md-6 col-md-offset-3">
                        <div class="alert alert-warning fade in alert-dismissable" style="width:50%;margin-top:18px;">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                            <strong>Proceso Pendiente!</strong> El hotel se comunicará con Ud. a la brevedad.
                        </div>
                    </div>
                @else
                    <div class="col-md-6 col-md-offset-3">
                        <div class="alert alert-danger fade in alert-dismissable" style="width:50%;margin-top:18px;">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                            <strong>Falló el proceso de compra</strong> Intente realizar la compra nuevamente
                        </div>
                    </div>
                @endif
            </div>
        </article>
    </section>

    @include('includes.web.promo-cuenta')
@endsection

resources/views/app/web/recover.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class="top_content">
            <div>
                <form class="form" method="post">
                    <h1>login</h1>
                    <div>
                        <input type="text" placeholder="NOMBRE DE USUARIO">
                    </div>
                    <div>
                        <input type="password" placeholder="PASSWORD">
                    </div>
                    <button name="login" class="botones" type="submit" id="login">LOGIN</button>
                    <div class="links_into_form">
                        <a href="{{ route('web.register') }}">aún no tenés cuenta?</a>
                        <a href="{{ route('web.recover') }}">olvidaste tus datos de acceso?</a>
                    </div>
                </form>
            </div>
        </article>
    </section>
@endsection

resources/views/app/web/reservation-success.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="alert alert-success fade in alert-dismissable" style="margin-top:18px;">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                    <strong>La reserva se ha enviado con éxito</strong> En breve se cumunicarán con usted para realizar los próximos pasos.
                    <div>Puede ver los datos de la reserva haciendo click <a href="{{ route('web.history') }}">aquí</a></div>
                </div>
            </div>
        </article>
    </section>

    @include('includes.web.promo-cuenta')
@endsection

@section('scripts')
    @include('includes.web.scripts.reservation')
@endsection

resources/views/app/web/reservations.blade.php
@extends('layouts.web')
@section('content')
    <section>
        <article class="top_content">
            <div>
                <div class="filtrado_rapido" id="filtrado_reservas">
                    @include('includes.web.booking-form')
                </div>
            </div>
        </article>
    </section>

    @include('includes.web.promo-cuenta')
@endsection

@section('scripts')
    @include('includes.web.scripts.reservation')
@endsection